### PR TITLE
Use the async api when a connection error triggers a slot update

### LINKED ISSUE #142: Time taken to return to application from hiredis library seems to be too long (>60sec)
Hi,

Encountered a case wherein the processing seems to be stuck at hiredis-cluster library and not returning to application for more than 60seconds. There is a mechanism we have in place to check if a thread is taking longer to report a heartbeat, which is getting missed in this case, and results in an exception being thrown.

This is the backtrace from the flow:

```
<hearbeat missing for long time resulting in a signal/crash in above frames>
#7  0x00007eff1914d90f in poll () from /lib64/libc.so.6
#8  0x00007eff1ab5a2ba in redisContextWaitReady (c=c@entry=0x26bac60, msec=msec@entry=2000) at net.c:250
#9  0x00007eff1ab5a991 in _redisContextConnectTcp (c=c@entry=0x26bac60, addr=<optimized out>, port=<optimized out>, timeout=<optimized out>,  source_addr=<optimized out>) at net.c:504
#10 0x00007eff1ab5aaa5 in redisContextConnectBindTcp (c=c@entry=0x26bac60, addr=<optimized out>, port=<optimized out>, timeout=<optimized out>, source_addr=<optimized out>) at net.c:544
#11 0x00007eff1ab592d7 in redisConnectWithOptions (options=options@entry=0x7ffc201f96e0) at hiredis.c:818
#12 0x00007eff1ab406b4 in ctx_get_by_node (cc=cc@entry=0x2859000, node=node@entry=0x2b085f0) at hircluster.c:1993
#13 0x00007eff1ab409b1 in node_get_which_connected (cc=cc@entry=0x2859000) at hircluster.c:2052
#14 0x00007eff1ab4990a in cluster_config_get (config_name=0x7eff1ab4a7ad "cluster-node-timeout", config_value_len=<synthetic pointer>, cc=0x2859000) at hircluster.c:2072
#15 redisClusterAsyncRetryCallback (ac=0x2821dc0, r=0x0, privdata=0x2b1e270) at hircluster.c:3926
#16 0x00007eff1ab55e09 in __redisRunCallback (reply=0x0, cb=0x7ffc201f9820, ac=0x2821dc0) at async.c:288
#17 __redisAsyncFree (ac=0x2821dc0) at async.c:310
#18 0x00007eff1ab566b9 in __redisAsyncDisconnect (ac=<optimized out>) at async.c:402
#19 0x00007eff1ab56765 in __redisAsyncHandleConnectFailure (ac=0x2821dc0) at async.c:604
#20 __redisAsyncHandleConnect (ac=ac@entry=0x2821dc0) at async.c:617
#21 0x00007eff1ab56e5e in redisAsyncHandleRead (ac=0x2821dc0) at hiredis/async.c:655
#22 0x00007eff1960f243 in AdapterEvents::redisLibmyeventHandler (this=0x26bb8c0, fd=20, events=29, info=...) at hiredis_libmyevent.h:89
<application trying to do a socket read in below frames>
```
From what I could gather from the backtrace and frames, this is the flow of events:

1. application attempts a read event as part of epoll event seen on the socket.
2. As part of redisAsyncHandleRead() operation, hiredis tries to connect() to a specific redis server node as part of __redisAsyncHandleConnect().
3. connect() fails with error: "Connection timeout", which triggers a __redisAsyncFree() operation which tries to clean up all outstanding commands (for which response is not received) to that particular redis server node.
4. There seems to be around 128 outstanding commands in the obuf of this particular redis server node at this point.
5. hiredis runs a while loop over all these outstanding commands and makes callbacks with empty reply to the hiredis-cluster/application.
6. hiredis-cluster processing these callbacks as part of redisClusterAsyncRetryCallback(), keeps track of failure responses, and it sees 5 failing responses, and decides to relearn the topology after a specified timeout("cluster-node-timeout") configured at the server.
7. For fetching "cluster-node-timeout" value from the redis server, hiredis-cluster frames a new command and tries to connect to one of the previously discovered nodes (added below decoded from the frames).
192.168.65.161, 192.168.121.79, 192.168.235.38, 192.168.221.225, 192.168.2.202, 192.168.165.198, 192.168.121.12, 192.168.165.182
8. hiredis-cluster follows the above order in attempting connection to the redis server ips, and in doing so it (redisConnectWithOptions()) performs a blocking connect() call to each of the server ips.
9. The time where the hearbeattimeout occurred, hiredis-cluster was attempting to connect to the 6th ip (192.168.165.198). So, the previous 5 attempts had failed in connecting and could account for a long time since the calls are all blocking.

I assume the analysis above holds good here. If this is the case, is there a way or suggestion to improve this? Do you see any other way of doing this that it doesn't get stuck at hiredis-cluster in processing.

@bjosv

### PR DESCRIPTION
**Pull request by bjosv**
When a command response indicates a communication error the slot map is updated.
This is now updated using the async api to avoid blocking calls to connect when querying a cluster node.

This fixes the problem with hanging connects that blocks the event handling system.

**Changed behaviors**
Previously communication errors were counted. When the client had received more errors that the configured max_retry_count value the Redis configuration "cluster-node-time" was fetched from a cluster node. This configured value was then used to determine when to perform a slotmap update. When an additional error was received after the time-to-wait the slotmap update procedure started. This procedure used blocking calls on a new TCP connection.

After this PR a communication error triggers the slotmap update procedure directly.
Primarily a connected node is selected that is found close to a randomly picked index of all known nodes.
The random index should give a more even distribution of selected nodes.
If no connected node is found while iterating to this index the remaining nodes are also checked until a connected node is found. If no connected node is found; a node close o the picked index, for which a connection establishment has not been attempted within throttle-time, is selected.
The commands are sent using the async api to avoid blocking sends (or connects). During the time the slotmap update procedure runs and until a second after it is finish other sent commands that triggers communication errors/timeouts will not start additional slotmap updates, ie the slotmap update is throttled.

**Other:**
Using async-api during MOVED should be implemented as well, but done in other PR.

Fixes #142

### CODE REVIEW

File: hircluster.c [hunk 1]
```diff
@@ -3781,6 +3701,132 @@ static void redisClusterAsyncCallback(redisAsyncContext *ac, void *r,
...
+void clusterSlotsReplyCallback(redisAsyncContext *ac, void *r, void *privdata) {
+    UNUSED(ac);
+    redisClusterAsyncContext *acc = (redisClusterAsyncContext *)privdata;
+    redisClusterContext *cc = acc->cc;
+    acc->update_route_time = hi_usec_now() + SLOTMAP_UPDATE_THROTTLE_USEC;
+
+    if (r == NULL) {
+        /* Ignore failures, next random node is hopefully working */
+        return;
+    }
```
Comment (zuiderkwast) [inline hircluster.c:3714]: Should we set update_route_time even if r == NULL?

Shouldn't we trigger another slot update with a different node here?

File: hircluster.c [hunk 2]
```diff
@@ -1189,6 +1193,89 @@ dict *parse_cluster_nodes(redisClusterContext *cc, char *str, int str_len,
...
 
+/* Update known cluster nodes with a new collection of redisClusterNodes.
+ * Will also update the slot-to-node lookup table for the new nodes. */
+static int updateNodesAndSlotmap(redisClusterContext *cc, dict *nodes) {
+    if (nodes == NULL) {
+        return REDIS_ERR;
+    }
+
+    /* Create a slot to redisClusterNode lookup table */
+    redisClusterNode **table;
```
Comment (zuiderkwast) [inline hircluster.c:1204]: If this function is placed after cluster_update_route_by_addr() it would be a smaller diff. The bulk of this code would not have been moved.

File: hircluster.c [hunk 3]
```diff
@@ -3781,6 +3701,132 @@ static void redisClusterAsyncCallback(redisAsyncContext *ac, void *r,
...
+            }
+        }
+    }
+    return NULL;
+}
+
+/* Return a random node. */
+static redisClusterNode *getRandomNode(dict *nodes) {
+    dictIterator di;
+    dictInitIterator(&di, nodes);
```
Comment (zuiderkwast) [inline hircluster.c:3778]: dict.c had support for picking random element, but maybe it was deleted from our copy of dict. The first few lines in dict.c mentions this:

```C
/* Hash table implementation.
 *
 * This file implements in memory hash tables with insert/del/replace/find/
 * get-random-element operations. Hash tables will auto resize if needed
```

File: hircluster.c [hunk 4]
```diff
@@ -3781,6 +3701,132 @@ static void redisClusterAsyncCallback(redisAsyncContext *ac, void *r,
...
+    if (updateNodesAndSlotmap(cc, nodes) != REDIS_OK) {
+        /* Ignore failures for now */
+    }
+}
+
+/* Return a random active node with async connection. */
+static redisClusterNode *getRandomActiveNode(dict *nodes) {
+    redisClusterNode *node;
+    dictIterator di;
+    dictInitIterator(&di, nodes);
```
Comment (zuiderkwast) [inline hircluster.c:3744]: Can getRandomNode and RandomActiveNode be combined into one that prefers an active node? Traversing the nodes 4 times seems like a waste if there are 1000 nodes...

Perhaps it doesn't need to be completely fair either. We could for example pick one out of the first 10 nodes. Only if none of them is connected we can continue beyond that and pick the first connected node.

**Review by zuiderkwast — COMMENTED** [review]
Very good! A few comments and questions.

File: hircluster.c (hunk 1 above)
Comment (bjosv) [reply hircluster.c:3715]: This was a bit simplified as a start.
Hiredis calls the callback-function with a NULL reply when either the command has timedout, or when there is connection errors.

The scenario I thought of:
If a slot map update don't find any connected node it will take a random node and start an async connect, it will also send/give the CLUSTER SLOTS command to hiredis for it to send it when the connection is up.
If the connect fails this callback is called with a NULL reply, due to the outstanding CLUSTER SLOTS command.
If all redis nodes are gone (like in the issue we have) I was afraid slotmap updates would go into a busy-loop.

One option could be to only trigger a new slotupdate to one of connected nodes, if that exists.
This would speedup updates for timeout cases, or temporary node issues.
..or some bookkeeping to avoid busy-looping cases..

Comment (zuiderkwast) [reply hircluster.c:3715]: I think we want a loop until we have a slot map, but wait one second between each attempt. (That's what we do in ered.)

Comment (bjosv) [reply hircluster.c:3715]: Waiting a second is the problem here, hiredis owns the eventloop and its timers.
We need to add a interface and functionality to each event-adapter to be able to kick-off timers in each eventsystem (or have hiredis expose something).

The modularity and being able to choose an own eventsystem its a bit annoying :-)
We have users that has implemented an own eventsystem as well, so updating existing adapters might not be enough for everybody.

Comment (bjosv) [reply hircluster.c]: The PR is now updated to retry until all nodes has been attempted (by using a lastConnectionAttempt and throttling).
Since there are no timerhandling available yet to hiredis-cluster the first slotmap update attempt is triggered by the user via a command, the retries are triggered by the NULL-reply callback.

File: hircluster.c (hunk 4 above)
Comment (bjosv) [reply hircluster.c]: The selection is now reworked.
1 of the 4 first found connected nodes are chosen, and if no connected nodes are found the last node that has not been used within 1 second is used (i.e a connection has not been attempted within 1 sec)

File: hircluster.c [hunk 5]
```diff
@@ -3773,6 +3697,124 @@ static void redisClusterAsyncCallback(redisAsyncContext *ac, void *r,
...
+                hi_usec_now() + SLOTMAP_UPDATE_THROTTLE_USEC;
+        }
+        return;
+    }
+
+    dict *nodes = parse_cluster_nodes(cc, reply->str, reply->len, cc->flags);
+    if (updateNodesAndSlotmap(cc, nodes) != REDIS_OK) {
+        /* Ignore failures for now */
+    }
+    acc->update_route_time = hi_usec_now() + SLOTMAP_UPDATE_THROTTLE_USEC;
```
Comment (zuiderkwast) [inline hircluster.c:3747]: This field, does it mean "when can we update slots next time"?

I think it's better that we store the current time, i.e. what time the slots were updated. This better matches lastConnectionAttempt we have on a node.

File: hircluster.c [hunk 6]
```diff
@@ -3773,6 +3697,124 @@ static void redisClusterAsyncCallback(redisAsyncContext *ac, void *r,
...
+        node = dictGetEntryVal(de);
+        if (node->acon != NULL && node->acon->err == 0 &&
+            node->acon->c.flags & REDIS_CONNECTED) {
+            foundConnected += 1;
+
+            if (foundConnected == 1) {
+                selected = node; /* Always keep the first found */
+            } else if ((random() % 4 + 1) == 4) {
+                selected = node; /* Select node when a random value 1-4 is 4 */
+            }
```
Comment (zuiderkwast) [inline hircluster.c:3774]: Why random() in every iteration in the loop? It's hard to see this is a fair random. Why not pick a random index before the loop?

File: hircluster.h [hunk 7]
```diff
@@ -142,6 +141,8 @@ typedef struct redisClusterAsyncContext {
     int err;          /* Error flags, 0 when there is no error */
     char errstr[128]; /* String representation of error when applicable */
 
+    int64_t update_route_time; /* Timestamp for next allowed slotmap update */
```
Comment (zuiderkwast) [inline hircluster.h:144]: The name of this variable could indicate if this is "next allowed" or "last successful" or "last attempt". It would be useful to see this from the variable name.

Btw, I suggested in another comment to store the last attempt timestamp instead. It seems more in line which last connect attempt for nodes.

**Review by zuiderkwast — COMMENTED** [review]
Much nicer now, to use an existing connection.

Is there any way to see how many requests are pending on a connection? Just thinking about the case the CLUSTER SLOTS will be added to a very long pipeline and therefore be delayed... Maybe not a valid convern?

File: hircluster.c (hunk 6 above)
Comment (zuiderkwast) [reply hircluster.c:3774]: Sorry, I see now why we want to pick the current node with 25% probability. It works regardless of how many nodes we have. (I guess it's not a fair distribution if we have only 2 or 3 nodes, but I'm not sure it's important. Or is it? Maybe 3 is a very common number of masters in a small cluster...)

File: hircluster.c (hunk 5 above)
Comment (bjosv) [reply hircluster.c]: Updated to use a lastSlotmapUpdateAttempt set with current time

File: hircluster.h (hunk 7 above)
Comment (bjosv) [reply hircluster.h]: Updated to lastSlotmapUpdateAttempt

File: hircluster.c (hunk 6 above)
Comment (bjosv) [reply hircluster.c]: Updated now to first perform 3 attempts to randomly pick a connected node, or else select any node that has not been attempted very recently.

**Comment by bjosv** [comment]
Ouch, the randomness makes the simulated-redis tests a bit harder to handle..

File: hircluster.c (hunk 6 above)
Comment (zuiderkwast) [reply hircluster.c]: Yes, it looks very simple and nice now! I like it.

**Comment by zuiderkwast** [comment]
> Ouch, the randomness makes the simulated-redis tests a bit harder to handle..

Right :-) We can inject some fake-randomness just for testing, e.g. using an ifdef or a known fixed random seed.

File: hircluster.c [hunk 8]
```diff
@@ -3741,34 +3738,42 @@ void clusterNodesReplyCallback(redisAsyncContext *ac, void *r, void *privdata) {
...
+        /* Keep any connected node */
+        if (node->acon != NULL && node->acon->err == 0 &&
+            node->acon->c.flags & REDIS_CONNECTED) {
+            connected = node;
+        }
+        /* Keep any node which has not been attempted within throttle limits */
         if (node->lastConnectionAttempt < throttleLimit) {
-            return node;
+            accepted = node;
+        }
```
Comment (zuiderkwast) [inline hircluster.c]: Idea: We only need to keep one, let's say `selected`. Maybe it doesn't make it more clear. You can decide.

```C
        /* Keep any connected node */
        if (node->acon != NULL && node->acon->err == 0 &&
            node->acon->c.flags & REDIS_CONNECTED) {
            selected = node;
        } else if ((selected == NULL || selected->acon == NULL) &&
                   node->lastConnectionAttempt < throttleLimit) {
            /* Keep any node which has not been attempted within throttle limits */
            selected = node;
        }
```

File: hircluster.c [hunk 9]
```diff
@@ -3741,34 +3738,42 @@ void clusterNodesReplyCallback(redisAsyncContext *ac, void *r, void *privdata) {
...
+        /* Return a connected or accepted node when chosen index is reached */
+        if (currentIndex >= checkIndex) {
+            if (connected != NULL)
+                return connected;
+            if (accepted != NULL)
+                return accepted;
         }
```
Comment (zuiderkwast) [inline hircluster.c]: Corner case: `checkIndex == 0` and the first node is not connected. In this case, we would pick the first node even if it's not connected.

To avoid it, we can run a few more steps to look for a connected node, before we return accepted.

```suggestion
        /* Return a connected or accepted node when chosen index is reached */
        if (currentIndex >= checkIndex && connected != NULL)
            return connected;
        else if (currentIndex >= checkIndex + 2 && accepted != NULL)
            return accepted;
```

**Review by zuiderkwast — COMMENTED** [review]
Pretty clean algorithm now. I like it. However, I found a corner case that might need to be addressed.

File: hircluster.c (hunk 9 above)
Comment (bjosv) [reply hircluster.c]: Hum, this would depend on the amount of nodes
If we only have one node, and that one is not connected but accepted, this would return NULL/none then?
Same with two nodes.

Comment (zuiderkwast) [reply hircluster.c]: Yes, should be safe. The `while ((de = dictNext(&di)) != NULL) {}` breaks the loop when there are no more nodes in the list.

Comment (bjosv) [reply hircluster.c]: Easy fixable, added a new fixup commit

**Review by zuiderkwast — APPROVED** [review]
