### PR TITLE
Fix problems during async node disconnects

### LINKED ISSUE #105: Assert while the Nodes are down
Hello,

We have a test that repeatedly kills all the Master Nodes & brings the cluster back up every 5 seconds, while the application is continuously making Async API calls using `redisClusterAsyncCommand()` 

During this we noticed the following assert:

`File: /home/osboxes/hiredis-cluster/hircluster.c Line: 3694: 0
[0] /usr/local/lib/libhiredis_cluster.so.0.7(actx_get_by_node+0x69) [0x7ffff7f92cd4]
[1] /usr/local/lib/libhiredis_cluster.so.0.7(redisClusterAsyncFormattedCommand+0x25e) [0x7ffff7f93963]
[2] /usr/local/lib/libhiredis_cluster.so.0.7(redisClustervAsyncCommand+0xc2) [0x7ffff7f93d68]
[3] /usr/local/lib/libhiredis_cluster.so.0.7(redisClusterAsyncCommand+0xca) [0x7ffff7f93e5a]`

The code at the above line points to `NOT_REACHED()` call inside `actx_get_by_node()`

How do we avoid the assert here? 
We understand `redisClusterAsyncCommand()` will fail in this case which is fine, but we would like to continue waiting till the Nodes are back up rather that exiting at this point.

Thank you.

### PR DESCRIPTION
**Pull request by bjosv**
This PR fixes 3 async issues:
1. When a node is removed all registered command callbacks are called with a NULL response.
This can happen when a new cluster topology is fetched. During this command callback handling
a NULL response might trigger the use of the nodes dict that is currently under deletion, which triggers a crash.
By making sure the nodes dict is replaced before we delete the old one a crash is avoided.
2. Return an error instead of asserting when a user attempts to send a command while a connection is disconnecting.
3. Correcting possible memory issue during MOVED handling.

Fixes #105

### CODE REVIEW

File: hircluster.c [hunk 1]
```diff
@@ -3630,7 +3637,10 @@ redisAsyncContext *actx_get_by_node(redisClusterAsyncContext *acc,
         if (ac->c.err == 0) {
             return ac;
         } else {
-            NOT_REACHED();
+            /* Disconnect ongoing and __redisAsyncDisconnect() will eventually */
+            /* call unlinkAsyncContextAndNode() before freeing the context.    */
+            __redisClusterAsyncSetError(acc, ac->c.err, ac->c.errstr);
+            return NULL;
```
Comment (zuiderkwast) [inline hircluster.c:3643]: I don't fully understand the comment. I suppose there is a context but it is invalid or has an error set. (Its corresponding comment in the PR description "a user attempts to send a command while a connection is disconnecting".)

Can you explain it better, possibly split into two sentences?

Comment (bjosv) [reply hircluster.c]: Good, have updated comments with something more understandable I think

File: hircluster.c [hunk 2]
```diff
@@ -3637,8 +3637,11 @@ redisAsyncContext *actx_get_by_node(redisClusterAsyncContext *acc,
         if (ac->c.err == 0) {
             return ac;
         } else {
-            /* Disconnect ongoing and __redisAsyncDisconnect() will eventually */
-            /* call unlinkAsyncContextAndNode() before freeing the context.    */
+            /* The cluster node has a hiredis context with errors. Hiredis
+             * will asynchronously destruct the context and unlink it from
+             * the cluster node object. Return an error until done.
+             * An example scenario is when sending a command from a command
+             * callback, which has a NULL reply due to a disconnect. */
```
Comment (zuiderkwast) [inline hircluster.c:3644]: Very nice!

**Review by zuiderkwast — APPROVED** [review]
