### PR TITLE
Fix code for XREAD and XREADGROUP and add test case

### LINKED ISSUE #186: Failed to find keys of command XREADGROUP
The following command is throwing an error. Why isn't this format supported?
XREADGROUP GROUP XX XX COUNT 1 STREAMS XX >

### PR DESCRIPTION
**Pull request by zuiderkwast**
The code for finding keys in XREAD and XREADGROUP commands was untested and incorrect. Here it is fixed and a test case is added.

Fixes #186

### CODE REVIEW

**Comment by zyhuf** [comment]
image
It seems that the 'startfrom' variable has lost its significance in the code. Should it be removed? Please confirm the code logic.
@zuiderkwast

**Comment by bjosv** [comment]
LGTM!
I'll guess we already had a testcase for XREAD then?

File: command.c [hunk 1]
```diff
@@ -274,28 +274,29 @@ void redis_parse_cmd(struct cmd *r) {
...
         arglen = arg1_len;
-        while (argidx < startfrom) {
+        while (argidx < (int)rnarg - 1) {
             if ((p = redis_parse_bulk(p, end, &arg, &arglen)) == NULL)
                 goto error; /* Keyword not provided, thus no keys. */
-            argidx++;
+            if (argidx++ < startfrom)
+                continue; /* Keyword can't appear in a position before 'startfrom' */
+            if (!strncasecmp(keyword, arg, arglen)) {
+                /* Keyword found. Now the first key is the next arg. */
```
Comment (zuiderkwast) [inline command.c:286]: @zyhuf We need to skip all arguments before 'startfrom', like this. Otherwise we have a problem if the group name or the consumer name is 'stream'.

Comment (zyhuf) [reply command.c:286]: I ran the modified code locally, and the test still showed an error, as indicated below.
“Failed to find keys of command”

Then, after I removed the reference to 'startfrom,' it ran successfully. @zuiderkwast

**Comment by zuiderkwast** [comment]
> I'll guess it would be nice to add a test for XREAD as well?

OK, done. Also changed the test for XREADGROUP so the group name and the consumer name are "streams", to make sure we don't mistake those for the STREAMS keyword (i.e. if we don't respect `startfrom` we would get the wrong result).

File: command.c (hunk 1 above)
Comment (zyhuf) [reply command.c:286]: I figured out the reason, thank you for the explanation. @zuiderkwast

**Review by bjosv — APPROVED** [review]
Nice.
