### PR TITLE
Fix issue of sending commands from reply callback

### LINKED ISSUE #124: Crash while doing dictRelease
Hi,

Came across one more crash scenario.
The top frames look similar to ticket raised before: https://github.com/Nordix/hiredis-cluster/issues/113

However, the bt leading to it is different.

```
[Current thread is 1 (Thread 0x7f22b4e9ba40 (LWP 38))]
(gdb) bt
#0  actx_get_by_node (acc=acc@entry=0x7b1a20, node=0x1c351e0)
    at hircluster.c:3631
#1  0x00007f22b84ef01c in redisClusterAsyncFormattedCommand (acc=acc@entry=0x7b1a20,
    fn=fn@entry=0x7f22b815d040 <optimized out>, privdata=privdata@entry=0x0,
    cmd=0xac9c90 <optimized out>, len=86)
    at hircluster.c:4124
#2  0x00007f22b84ef31b in redisClustervAsyncCommand (acc=0x7b1a20,
    fn=0x7f22b815d040 <optimized out>, privdata=0x0, format=<optimized out>,
    ap=ap@entry=0x7ffdb96af2b0) at hircluster.c:4251
#3  0x00007f22b84ef42e in redisClusterAsyncCommand (acc=<optimized out>, fn=<optimized out>, privdata=<optimized out>, format=<optimized out>)
    at hircluster.c:4265

Frames 4 and 5 are application frames, where it processes callback from hiredis and again issues a new command for execution.

#6  0x00007f22b84ef6e5 in redisClusterAsyncRetryCallback (ac=<optimized out>, r=0x0, privdata=0x7b75b0)
    at hircluster.c:4016
#7  0x00007f22b84d0e09 in __redisRunCallback (reply=0x0, cb=0x7ffdb96af690, ac=0x1e091a0)
    at hiredis/async.c:288
#8  __redisAsyncFree (ac=0x1e091a0) at hiredis/async.c:310
#9  0x00007f22b84d1618 in redisAsyncFree (ac=0x1e091a0) at hiredis/async.c:375
#10 0x00007f22b84e5ee5 in cluster_node_deinit (node=node@entry=0x8865c0)
    at hircluster.c:281
#11 0x00007f22b84e6015 in cluster_node_deinit (node=0x8865c0)
    at hircluster.c:264
#12 dictClusterNodeDestructor (privdata=<optimized out>, val=0x8865c0)
    at hircluster.c:133
#13 0x00007f22b84e5616 in _dictClear (ht=0x88ef80) at dict.c:179
#14 dictRelease (ht=0x88ef80) at dict.c:194
#15 0x00007f22b84eac44 in cluster_update_route_by_addr (port=<optimized out>, ip=<optimized out>, cc=<optimized out>)
    at hircluster.c:1390
#16 cluster_update_route (cc=cc@entry=0x7b1920) at hircluster.c:1463
#17 0x00007f22b84efa65 in actx_get_after_update_route_by_slot (slot_num=4682, acc=0x7b1a20)
    at hircluster.c:3737
#18 redisClusterAsyncRetryCallback (ac=<optimized out>, r=0x919570, privdata=0x169d230)
    at hircluster.c:3972
#19 0x00007f22b84d190c in __redisRunCallback (reply=<optimized out>, cb=0x7ffdb96af920, ac=0x7b9650)
    at hiredis/async.c:288
#20 redisProcessCallbacks (ac=0x7b9650) at hiredis/async.c:580

Below frames, eventloop detects a socket event and calls into hiredis.

```

Looks like there is multiple back and forth jumping between hiredis and application, and eventually leading to a crash. The node, table, slots are all having junk data at frame 0. However, nodes dictionary is intact similar to how ticket https://github.com/Nordix/hiredis-cluster/issues/113 was having.

Atleast the below piece of code explains why nodes dictionary is intact.

```
    /* Replace cc->nodes before releasing the old dict since
     * the release procedure might access cc->nodes. */
    oldnodes = cc->nodes;
    cc->nodes = nodes;
    if (oldnodes != NULL) {
        dictRelease(oldnodes);
    }
```
 
But we don't update slots and table as part of this, not sure if that is intentional. Can you please check this stack and see what can lead to this/suggest a solution?

cc: @bjosv 

Thanks.

### PR DESCRIPTION
**Pull request by bjosv**
When nodes are removed their outstanding requests are "cancelled" by giving a NULL reply to their callbacks.
If a user resends a command from this callback the slot-to-node information (`cc->table`) might be wrong,
pointing to a removed `cluster_node`.

Changing the order of removal fixes the problem, indicated by the added testcase.

Fixes #124

### CODE REVIEW

File: hircluster.c [hunk 1]
```diff
@@ -1383,30 +1383,33 @@ static int cluster_update_route_by_addr(redisClusterContext *cc, const char *ip,
...
-
     if (cc->slots != NULL) {
         cc->slots->nelem = 0;
         hiarray_destroy(cc->slots);
     }
     cc->slots = slots;
 
+    /* Update slot-to-node table before changing cc->nodes since
+     * removal of nodes might trigger user callbacks.
+     * Required if commands are sent from these callbacks. */
```
Comment (zuiderkwast) [inline hircluster.c:1394]: In the second sentence, it's slightly unclear what is required. How about something like this?

```suggestion
    /* Update slot-to-node table before changing cc->nodes since
     * removal of nodes might trigger user callbacks which may
     * send commands, which depend on the slot-to-node table. */
```

File: tests/clusterclient_async_sequence.c [hunk 2]
```diff
@@ -5,13 +5,15 @@
...
- #          command. This is the default behaviour.
+ * clusterclient_async.c using following action commands:
+ *
+ * !async  - Send multiple commands and then wait for their responses.
+ *           Will send all following commands until EOF or the command `!sync`
+ *
+ * !sync   - Send a single command and wait for its response before sending next
+ *           command. This is the default behaviour.
+ *
+ * !resend - Resend a failed command from its reply callback.
```
Comment (zuiderkwast) [inline tests/clusterclient_async_sequence.c:16]: Does `!resend` activate resending for all failed commands for the rest of the session?

File: tests/scripts/command-from-callback-test.sh [hunk 3]
```diff
@@ -0,0 +1,122 @@
...
+SLEEP 1
+SEND -MOVED 12182 127.0.0.1:7401
+EXPECT CLOSE
+EOF
+server3=$!
+
+# Wait until all nodes are ready to accept client connections
+wait $syncpid1 $syncpid2 $syncpid3;
+
+# Run client
```
Comment (zuiderkwast) [inline tests/scripts/command-from-callback-test.sh:77]:
```suggestion
# Run client which resends failed commands in the reply callback
```

**Review by zuiderkwast — COMMENTED** [review]
Nice!

File: tests/clusterclient_async_sequence.c (hunk 2 above)
Comment (bjosv) [reply tests/clusterclient_async_sequence.c:16]: Updated text
