### PR TITLE
No assert in the callback handling when a node is already removed

### LINKED ISSUE #111: redisClusterAsyncRetryCallback crash after command timeout
Hello,

We are using hiredis-cluster Release 0.8.1, and this issue is with regards to a crash we see in our performance testing.

We use async hiredis APIs, and invoke them both from the application and also from hiredis callbacks.
Our application is multi-threaded, and hiredis context object & hiredis API calls are mutex protected.
Our adapter is designed as per the reference hiredis adapter, and we don't do anything special besides calling into hiredis library.
 
We see the following crash a few hours into our test following an adapter timeout:

Crash reason:  SIGSEGV /SEGV_MAPERR
Crash address: 0x1c
Process uptime: not available

Thread 0 (crashed)
`0  libhiredis_cluster.so.0.8!redisClusterAsyncRetryCallback + 0x263`
`1  libhiredis.so.1.0.0!__redisAsyncFree + 0x69`
`2  libhiredis.so.1.0.0!redisProcessCallbacks + 0x1a0`
`3  redisLibmyeventHandler(int, unsigned int, base::SystemInfo) [hiredis_libmyevent.h : 89 + 0x5]`

Please help debug the issue. Let me know if you need any further information.

Thank you.

### PR DESCRIPTION
**Pull request by bjosv**
When a context is freed all its callbacks are called with a NULL response.
During the callback handling there is an attempt to update the topology after a number of attempts.
If the node is removed during this topology change the context's pointer to the node will be cleared.
The callbacks that follows needs to be able to finish, i.e not asserting.

Added a testcase that can trigger the issue.
Since the [Redis config `cluster-node-timeout`](https://github.com/redis/redis/blob/ce4ebe6ba858bd6be7cabdc830f5ef30d6fcd37a/src/config.c#L3118) allows a 0 value this is also accepted (and used in the testcase).

Fixes #111

### CODE REVIEW

File: tests/clusterclient_async_sequence.c [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+        size_t len = strlen(cmd);
+        if (cmd[len - 1] == '\n') /* Chop trailing line break */
+            cmd[len - 1] = '\0';
+
+        if (cmd[0] == '\0') /* Skip empty lines */
+            continue;
+
+        if (cmd[0] == '#') { /* Check and skip comments */
+            int i;
+            if (sscanf(cmd, "# %d concurrent", &i) == 1) {
```
[the remark this answers is not in the document]
Comment (bjosv) [reply tests/clusterclient_async_sequence.c:70]: Yes, that is probably clearer. Will update

File: tests/clusterclient_async_sequence.c [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+ * This program connects to a Redis node and then reads commands from stdin, such
+ * as "SET foo bar", one per line and prints the results to stdout.
+ *
+ * The behaviour is similar to that of clusterclient_async.c, but it sends the
+ * next command after receiving a reply from the previous command.
+ * It is still possible to send multiple commands at once like in
+ # clusterclient_async.c using following action commands:
+ #
+ # !async - Send multiple commands and wait for their responses before sending next.
+ #          Will send all following commands until EOF or the command `!sync`
```
Comment (zuiderkwast) [inline tests/clusterclient_async_sequence.c:11]: This doesn't sound right: "wait for their response before sending next"... Shouldn't it be "wait for their responses after all commands are sent" or something like that?

File: tests/scripts/timeout-handling-test.sh [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+    exit $clientexit
+fi
+
+# Check the output from clusterclient
+cmp "$testname.out" <<'EOF' || exit 99
+OK
+unknown error
+unknown error
+unknown error
+unknown error
```
Comment (zuiderkwast) [inline tests/scripts/timeout-handling-test.sh:104]: I guess "unknown error" is fine and legacy, just wondering why isn't the response "timeout" or something like that?

**Review by zuiderkwast — APPROVED** [review]
Looks good!

File: tests/scripts/timeout-handling-test.sh (hunk 3 above)
Comment (bjosv) [reply tests/scripts/timeout-handling-test.sh:104]: When I tested using hiredis 1.1.0 the error string in the callback is set to `timeout` instead of not being set.
Not sure if there are other changes needed when lifting the version used, but we'll see..

Comment (zuiderkwast) [reply tests/scripts/timeout-handling-test.sh:104]: Interesting. I guess we need to tag a new version when we lift hiredis.
